CREATE TABLE CONTACT (
  id INT AUTO_INCREMENT PRIMARY KEY,
  phoneNumber VARCHAR(255) NULL,
  email VARCHAR(255) NULL,
  linkedId INT NULL,
  linkPrecedence ENUM('primary', 'secondary') NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deletedAt DATETIME NULL
);



CREATE TABLE CONTACT_LINK (
  secondaryContactId INT PRIMARY KEY,
  primaryContactId INT
);



CREATE TABLE CONSOLIDATED_CONTACT (
  primaryContactId INT PRIMARY KEY,
  consolidatedData JSON
);